In [1]:
#longstaff_schwartz
import numpy as np

x = np.array([[1.00, 1.09, 1.08, 1.34], 
             [1.00, 1.16, 1.26, 1.54],     
             [1.00, 1.22, 1.07, 1.03],
             [1.00, 0.93, .97, .92],
             [1.00, 1.11, 1.56, 1.52],
             [1.00, .76, .77, .9],
             [1.00, .92, .84, 1.01],
             [1.00, .88, 1.22, 1.34]])

In [2]:
x = x.T

In [20]:
x.shape

(4, 8)

In [3]:
payoff = np.maximum(1.1 - x, 0)


In [40]:
payoff.shape

(4, 8)

In [41]:
x.shape

(4, 8)

In [17]:
V = payoff[-1,:]
import matplotlib.pyplot as plt

for i in range(len(x)-2, 0, -1):
    # itm = payoff[i] > 0
    # x_itm = x[i+1][itm]
    rg = np.polyfit(x[i,:], payoff[i,:], 5)
    C = np.polyval(rg, x[i])
    V = np.where(payoff[i] > C, payoff[i], V*np.exp(-0.01*0.5))
    
    # print(np.where(payoff[i] > C, payoff[i], V*np.exp(-0.01*0.5)))

In [4]:
V = payoff[-1,:]

for i in reversed(range(1, x.shape[0] - 1)):
    # print(i)
    print(V.shape)
    x_ = x[i, : ]
    otm = np.where(x_ > 1.1)
    itm = np.where(x_ <= 1.1)
    itm_x = np.delete(x_, otm)
    itm_o = np.delete(V, otm)
    # print(np.where(itm == True, x_, 0))
    # # fit curve
    try:
        rg = np.polyfit(itm_x,  itm_o, 2)
        C = np.polyval(rg, itm_x)
    except Exception:
        pass
    # approximate continuation value
    print("\n")
    print(f"--------- continuation_{i} ---------")
    print("\n")
    print(rg)
    print("\n")
    print(f"--------- rg_{i} ---------")
    print("\n")
    print(C)
    print(len(payoff))
    V[itm] = np.where(payoff[i, itm] > C, payoff[i, itm], V[itm])

(8,)


--------- continuation_2 ---------


[-1.92572147  3.16789444 -1.136152  ]


--------- rg_2 ---------


[0.03901247 0.04873654 0.12479427 0.16136646 0.16609026]
4
(8,)


--------- continuation_1 ---------


[ 1.44033518 -3.5416957   2.16350507]


--------- rg_1 ---------


[0.01431898 0.11547396 0.30375393 0.12424472 0.16220841]
4


In [48]:
len(payoff[-1, :])

8

In [5]:
V

array([0.  , 0.  , 0.07, 0.17, 0.  , 0.34, 0.18, 0.22])